[tool.poetry]
name = "trader-auto"
version = "0.1.0"
description = ""
authors = ["clementremillieux <clement.remillieux@gmail.com>"]
readme = "README.md"
packages = [{include = "trader_auto"}]

[tool.poetry.dependencies]
python = "3.10.1"
pandas = "^2.2.3"
yfinance = "^0.2.56"
scikit-learn = "^1.6.1"
pydantic = "2.10.3"
python-dotenv = "^1.1.0"
numpy = "1.26.4"
alpaca-py = "^0.39.4"
matplotlib = "^3.10.1"
yahooquery = "^2.3.7"
cdp-sdk = "^1.4.0"
coinbase-advanced-py = "^1.8.2"
python-binance = "^1.0.28"
binance-futures-connector = "^4.1.0"
binance-connector = "^3.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
