# -*- coding: utf-8 -*-
"""trainer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HX5H6jZsQgY9oLF3AEQCTBkpAZLaeCWi
"""

from google.colab import drive

drive.mount("/content/drive")

"""logger_config.py"""
import os

import logging

from pydantic import BaseModel


class CustomFormatter(logging.Formatter):
    """Custom logger with colored output, aligned messages, and relative paths"""

    RED = "\033[31m"
    GREEN = "\033[92m"
    RESET = "\033[0m"
    ORANGE = "\033[41m"

    def format(self, record):
        """Format log records with color, alignment, and additional context"""

        original = super(CustomFormatter, self).format(record)

        if record.levelno == logging.INFO:
            level_name = self.GREEN + record.levelname + self.RESET

        elif record.levelno == logging.ERROR:
            level_name = self.RED + record.levelname + self.RESET

        elif record.levelno == logging.WARNING:
            level_name = self.ORANGE + record.levelname + self.RESET

        else:
            level_name = record.levelname

        project_root = (
            ""  # os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        )

        relative_path = ""  # os.path.relpath(record.pathname, project_root)

        module = record.module

        function_name = record.funcName

        line_no = record.lineno

        dynamic_part = (
            f"{level_name} -> [{relative_path}.{module}.{function_name}.{line_no}] :"
        )

        max_dynamic_length = 100

        padding = max(0, max_dynamic_length - len(dynamic_part))

        padded_original = original.rjust(padding + len(original))

        timestamp = self.formatTime(record, "%Y-%m-%d %H:%M:%S")

        return f"{timestamp} {dynamic_part}\t{padded_original}"


def setup_logging():
    """setup the logging logger"""

    logger = logging.getLogger("NOTEBOOK LLM")

    if logger.hasHandlers():
        logger.handlers.clear()

    handler = logging.StreamHandler()

    handler.setFormatter(CustomFormatter("%(message)s"))

    logger.setLevel(logging.INFO)

    logger.addHandler(handler)

    logger.propagate = False


def log_pydantic_model(model: BaseModel):
    """
    Logs the contents of a Pydantic model in a structured JSON format.

    Args:
        model (BaseModel): The Pydantic model instance to be logged.
    """

    logger_pydantic = logging.getLogger("NOTEBOOK LLM")

    pretty_json = model.model_dump_json(indent=4)

    logger_pydantic.info("\n%s:\n%s", model.__class__.__name__, pretty_json)


setup_logging()

logger = logging.getLogger("NOTEBOOK LLM")

"""YahooHandler module."""

import numpy as np

from datetime import datetime, timedelta

from typing import Dict

import pandas as pd

import yfinance as yf


class YahooHandler:
    """Class to handle Yahoo Finance API."""

    def __init__(self, ticker: str):
        self.ticker = ticker

        self.stock = yf.Ticker(ticker)

    def get_stock_data(self, interval: str, days: str) -> pd.DataFrame:
        """Function to get stock data from Yahoo Finance API."""

        start_date = datetime.now() - timedelta(days=int(days))

        start_time = start_date.strftime("%Y-%m-%d")

        end_date = datetime.now()

        end_time = end_date.strftime("%Y-%m-%d")

        df = self.stock.history(interval=interval, start=start_time, end=end_time)

        return df

    @staticmethod
    def get_static_features(info: Dict) -> None:
        """Function to get static features from Yahoo Finance API."""

        sector_str = info.get("sector", "Unknown")

        sector_hash = hash(sector_str)

        RANDOM_SEED = 10**8

        sector_numeric = (abs(sector_hash) % RANDOM_SEED) / RANDOM_SEED

        market_cap = float(info.get("marketCap", 0.0))

        book_value = float(info.get("bookValue", 0.0))

        price_to_book = float(info.get("priceToBook", 0.0))

        trailing_pe = float(info.get("trailingPE", 0.0))

        forward_pe = float(info.get("forwardPE", 0.0))

        revenue_growth = float(info.get("revenueGrowth", 0.0))

        earnings_growth = float(info.get("earningsGrowth", 0.0))

        gross_margins = float(info.get("grossMargins", 0.0))

        operating_margins = float(info.get("operatingMargins", 0.0))

        log_market_cap = np.log(market_cap + 1)

        static_features = np.array(
            [
                sector_numeric,
                log_market_cap,
                book_value,
                price_to_book,
                trailing_pe,
                forward_pe,
                revenue_growth,
                earnings_growth,
                gross_margins,
                operating_margins,
            ],
            dtype=float,
        )

        return static_features


from typing import List, Optional

from datetime import datetime as dt

from pydantic import BaseModel, ConfigDict


class Topic(BaseModel):
    """_summary_

    Args:
        BaseModel (_type_): _description_
    """

    topic: str

    relevance_score: float


class TickerSentiment(BaseModel):
    """_summary_

    Args:
        BaseModel (_type_): _description_
    """

    ticker: str

    relevance_score: float

    ticker_sentiment_score: float

    ticker_sentiment_label: str


class NewsItem(BaseModel):
    """_summary_

    Args:
        BaseModel (_type_): _description_
    """

    title: str

    url: str

    time_published: str

    content: Optional[str] = None

    authors: Optional[List[str]]

    summary: Optional[str]

    banner_image: Optional[str]

    source: str

    category_within_source: Optional[str]

    source_domain: str

    topics: Optional[List[Topic]]

    overall_sentiment_score: float

    overall_sentiment_label: str

    ticker_sentiment: Optional[List[TickerSentiment]]


class News(BaseModel):
    """_summary_

    Args:
        BaseModel (_type_): _description_
    """

    articles: List[NewsItem]


class PriceItem(BaseModel):
    """PriceItem model."""

    date: dt

    open: float

    high: float

    low: float

    close: float

    volume: float


class Stock(BaseModel):
    """Stock model."""

    stock: List[PriceItem]


class TickerData(BaseModel):
    """TickerData model."""

    name: str

    sql_db_id: Optional[str] = None

    news: Optional[News] = None

    stock: Optional[pd.DataFrame] = None

    model_config = ConfigDict(arbitrary_types_allowed=True)


class DatasetSignal(BaseModel):
    """DatasetSignal model."""

    column_name: str

    is_derivative: bool

    is_normalize: bool

    is_financial: bool


"""API a v handler module."""


class TickerHandler:
    """_summary_"""

    def __init__(self, name: str) -> None:
        self.name: str = name

        self.data = TickerData(name=name)

        self.data.stock = Stock(stock=[])

        self.yahoo_handler = YahooHandler(ticker=self.name)

    async def download_data(self, interval: str, days: str) -> None:
        """_summary_"""

        stock = self.yahoo_handler.get_stock_data(interval=interval, days=days)

        self.data.stock = stock


from typing import Tuple

import torch

from torch.utils.data import Dataset as TorchDataset


class MultiTaskSignalDataset(TorchDataset):
    """
    Renvoie:
        x      : (window, n_features)   — float32
        targets: dict{
            'cls': int64  (0/1/2)
            'ret': float32
            'vol': float32
        }
    """

    def __init__(
        self,
        X: torch.Tensor,
        y_cls: torch.Tensor,
        y_ret: torch.Tensor,
        y_vol: torch.Tensor,
    ):
        self.X = X
        self.y_cls = y_cls.long()  # CrossEntropy → int64
        self.y_ret = y_ret
        self.y_vol = y_vol

    def __len__(self) -> int:
        return len(self.X)

    def __getitem__(self, idx):
        return (
            self.X[idx],
            {"cls": self.y_cls[idx], "ret": self.y_ret[idx], "vol": self.y_vol[idx]},
        )


class TFTDataset(TorchDataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)

        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        x_sample = self.X[idx]

        y_sample = self.y[idx]

        return x_sample, y_sample


from typing import Union

import pandas as pd


def create_binary_signal(
    signal: Union[np.ndarray, pd.Series], N: int, c: float
) -> np.ndarray:
    """Creates a binary signal based on the growth of the input signal."""

    signal = np.asarray(signal, dtype=float)

    length = len(signal)

    binary_signal = np.zeros(length, dtype=float)

    for i in range(length - N):
        start_idx = i
        end_idx = i + N

        window = signal[start_idx : end_idx + 1]

        if np.any(window >= (1.0 + c) * signal[i]):
            binary_signal[i] = 2

        elif np.any(window >= (1.0 + (c / 2)) * signal[i]):
            binary_signal[i] = 1

        else:
            binary_signal[i] = 0

    return binary_signal


from numpy.typing import NDArray


def compute_balanced_indices(y_cls: np.ndarray) -> np.ndarray:
    """Retourne un array d'indices équilibrés 0/1/2—aucun shuffle externe."""

    idx0, idx1, idx2 = (np.where(y_cls == k)[0] for k in (0, 1, 2))

    print(f"0: {len(idx0)}, 1: {len(idx1)}, 2: {len(idx2)}")

    n = min(len(idx0), len(idx1), len(idx2))

    print(f"n: {n}")

    if n == 0:
        raise ValueError("Impossible d’équilibrer : une classe est vide.")

    np.random.shuffle(idx0)
    np.random.shuffle(idx1)
    np.random.shuffle(idx2)

    balanced = np.concatenate([idx0[:n], idx1[:n], idx2[:n]])

    np.random.shuffle(balanced)

    print(f"balanced: {len(balanced)}")

    return balanced


def create_sliding_window(data: np.ndarray, window_size: int) -> Optional[np.ndarray]:
    """
    Splits the dataset into overlapping packs of the specified size.

    Args:
        data (np.ndarray): The input time series data.
        window_size (int): The size of each sliding window.

    Returns:
        np.ndarray: A 2D array where each row corresponds to a window.
    """

    num_windows = data.shape[0] - window_size + 1

    if num_windows <= 0:
        logger.warning(
            f"Window size {window_size} is larger than the dataset length {data.shape[0]}."
        )

        return None

    return np.array([data[i : i + window_size] for i in range(num_windows)])


from typing import Any


class SignalDerivative:
    """Compute the derivative of a signal (instantaneous variation)."""

    @staticmethod
    def compute_derivative(signal: NDArray) -> NDArray:
        # Conversion en array NumPy pour éviter tout problème de Series
        signal_array = np.asarray(signal)
        return np.diff(signal_array, prepend=signal_array[0])


class SignalLogReturn:
    """Compute the log-return of a signal, useful for relative change measurement."""

    @staticmethod
    def compute_log_return(signal: NDArray) -> NDArray:
        # Assurer que le signal soit 1D
        signal_1d = signal.squeeze()  # Convertit (N,1) en (N,)

        log_prices = np.log(signal_1d)

        log_return = np.diff(log_prices, prepend=log_prices[0])

        return log_return


class SignalRollingVolatility:
    """Compute the rolling volatility of a signal over a given window."""

    @staticmethod
    def compute_rolling_volatility(signal: NDArray, window: int = 14) -> NDArray:
        # S'assurer que signal est de type float
        signal = signal.astype(float)

        vol = np.empty_like(signal)  # vol aura le même dtype que signal, donc float
        vol[:] = np.nan  # maintenant pas de soucis pour assigner NaN

        for i in range(len(signal)):
            start = max(0, i - window + 1)
            window_slice = signal[start : i + 1]
            vol[i] = np.std(window_slice) if len(window_slice) > 1 else 0.0

        return vol


class SignalMomentum:
    """Compute the momentum over a given period (difference between current and past values)."""

    @staticmethod
    def compute_momentum(signal: NDArray, period: int = 5) -> NDArray:
        # Convertir signal en float pour éviter les problèmes de type
        signal = signal.astype(float)

        # Maintenant mom sera aussi en float
        mom = np.empty_like(signal)

        mom[:] = np.nan

        for i in range(len(signal)):
            if i >= period:
                mom[i] = signal[i] - signal[i - period]

        return mom


class SignalRSI:
    """Compute the Relative Strength Index (RSI) of a signal."""

    @staticmethod
    def compute_rsi(signal: np.ndarray, period: int = 14) -> np.ndarray:
        # Ensure signal is a 1D float array
        signal = signal.flatten().astype(float)

        if len(signal) < 2:
            raise ValueError("Signal must have at least 2 data points to compute RSI.")

        # Initialize RSI with NaNs
        rsi = np.empty_like(signal)
        rsi[:] = np.nan

        # Calculate the differences (delta) of consecutive prices
        delta = np.zeros_like(signal)  # delta has the same shape as signal
        delta[1:] = np.diff(signal)  # The first delta is zero

        # Calculate gains and losses
        gains = np.where(delta > 0, delta, 0.0)
        losses = np.where(delta < 0, -delta, 0.0)

        # Calculate the initial rolling average for the first period
        if len(signal) <= period:
            raise ValueError(
                f"Signal must have more than {period} data points. Received {len(signal)} points."
            )

        avg_gain = np.mean(gains[:period])

        avg_loss = np.mean(losses[:period])

        if avg_loss == 0:
            rsi[period] = 100  # If there are no losses, RSI is 100

        else:
            rs = avg_gain / avg_loss

            rsi[period] = 100.0 - (100.0 / (1.0 + rs))

        # Use exponential moving average (EMA) for the subsequent RSI values
        for i in range(period + 1, len(signal)):
            avg_gain = (avg_gain * (period - 1) + gains[i]) / period
            avg_loss = (avg_loss * (period - 1) + losses[i]) / period

            if avg_loss == 0:
                rsi[i] = 100  # Avoid division by zero, if no losses, RSI = 100
            else:
                rs = avg_gain / avg_loss
                rsi[i] = 100.0 - (100.0 / (1.0 + rs))

        return rsi / 100


class SignalDateTime:
    """_summary_

    Returns:
        _type_: _description_
    """

    @staticmethod
    def compute_time_features(date_index: pd.DatetimeIndex) -> np.ndarray:
        """Compute unique linear time features for a week, normalized to [0, 1].

        Args:
            date_index (pd.DatetimeIndex): The index of dates to compute features for.

        Returns:
            np.ndarray: A 1D array of normalized linear values representing time over a week.
        """
        day_of_week = date_index.dayofweek.values

        hour = date_index.hour.values

        total_hours = day_of_week * 24 + hour

        normalized_features = total_hours / 168

        return normalized_features


class SignalMACD:
    """Compute the Moving Average Convergence Divergence (MACD) of a price signal."""

    @staticmethod
    def compute_macd(
        signal: NDArray, fast: int = 12, slow: int = 26, signal_period: int = 9
    ) -> List[NDArray]:
        """
        Compute the MACD line, signal line, and MACD histogram for the given price signal.

        Args:
            signal (NDArray): A 1D or 2D NumPy array of price data (e.g., closing prices).
            fast (int, optional): The period for the fast EMA. Defaults to 12.
            slow (int, optional): The period for the slow EMA. Defaults to 26.
            signal_period (int, optional): The period for the signal EMA. Defaults to 9.

        Returns:
            NDArray: A 2D array of shape (n_samples, 3) where:
                - column 0 = MACD line
                - column 1 = Signal line
                - column 2 = MACD histogram (macd_line - signal_line)
        """
        # Ensure signal is 1D
        signal_1d = signal.squeeze().astype(float)

        def compute_ema(prices: NDArray, period: int) -> NDArray:
            """Helper function to compute Exponential Moving Average (EMA)."""
            ema = np.zeros_like(prices)
            alpha = 2.0 / (period + 1.0)
            ema[0] = prices[0]
            for i in range(1, len(prices)):
                ema[i] = alpha * prices[i] + (1.0 - alpha) * ema[i - 1]
            return ema

        # Compute EMAs
        fast_ema = compute_ema(signal_1d, fast)
        slow_ema = compute_ema(signal_1d, slow)

        # MACD line
        macd_line = fast_ema - slow_ema

        # Signal line
        signal_line = compute_ema(macd_line, signal_period)

        # Histogram
        histogram = macd_line - signal_line

        return [
            np.asarray(macd_line).reshape(-1, 1),
            np.asarray(signal_line).reshape(-1, 1),
            np.asarray(histogram).reshape(-1, 1),
        ]


class SignalBollingerBands:
    """Compute Bollinger Bands for a price signal."""

    @staticmethod
    def compute_bollinger_bands(
        signal: NDArray, window: int = 20, num_std_dev: int = 2
    ) -> tuple[NDArray, NDArray, NDArray]:
        """
        Compute the Bollinger Bands over a moving window.

        Args:
            signal (NDArray): A 1D or 2D NumPy array of price data.
            window (int, optional): The window size for rolling mean and std. Defaults to 20.
            num_std_dev (int, optional): The number of standard deviations for the bands. Defaults to 2.

        Returns:
            tuple of NDArray: (upper_band, mid_band, lower_band) each of shape (n_samples,).
        """
        signal_1d = signal.squeeze().astype(float)

        # Initialize arrays
        upper_band = np.empty_like(signal_1d)
        mid_band = np.empty_like(signal_1d)
        lower_band = np.empty_like(signal_1d)

        upper_band[:] = np.nan
        mid_band[:] = np.nan
        lower_band[:] = np.nan

        for i in range(len(signal_1d)):
            start = max(0, i - window + 1)
            window_slice = signal_1d[start : i + 1]

            mean_val = np.mean(window_slice)
            std_val = np.std(window_slice)

            mid_band[i] = mean_val
            upper_band[i] = mean_val + num_std_dev * std_val
            lower_band[i] = mean_val - num_std_dev * std_val

        return (
            np.asarray(upper_band).reshape(-1, 1),
            np.asarray(mid_band).reshape(-1, 1),
            np.asarray(lower_band).reshape(-1, 1),
        )


class SignalStochasticOscillator:
    """Compute the Stochastic Oscillator (%K and %D) for a given price signal."""

    @staticmethod
    def compute_stoch_oscillator(
        high: NDArray,
        low: NDArray,
        close: NDArray,
        k_period: int = 14,
        d_period: int = 3,
    ) -> tuple[NDArray, NDArray]:
        """
        Compute the Stochastic Oscillator (%K and %D) based on high, low, and close prices.

        Args:
            high (NDArray): High prices (1D).
            low (NDArray):  Low prices (1D).
            close (NDArray): Close prices (1D).
            k_period (int, optional): Period for %K. Defaults to 14.
            d_period (int, optional): Smoothing period for %D (SMA of %K). Defaults to 3.

        Returns:
            tuple of NDArray: (stoch_k, stoch_d) each of shape (n_samples,).
        """
        high_1d = high.squeeze().astype(float)
        low_1d = low.squeeze().astype(float)
        close_1d = close.squeeze().astype(float)

        length = len(close_1d)
        stoch_k = np.empty(length)
        stoch_k[:] = np.nan
        stoch_d = np.empty(length)
        stoch_d[:] = np.nan

        # Compute %K
        for i in range(length):
            start = max(0, i - k_period + 1)
            window_high = high_1d[start : i + 1]
            window_low = low_1d[start : i + 1]

            highest_high = np.max(window_high)
            lowest_low = np.min(window_low)

            if highest_high - lowest_low == 0:
                stoch_k[i] = 0.0
            else:
                stoch_k[i] = (close_1d[i] - lowest_low) / (highest_high - lowest_low)

        # Compute %D (simple moving average of %K)
        for i in range(length):
            start = max(0, i - d_period + 1)
            window_k = stoch_k[start : i + 1]
            stoch_d[i] = np.nanmean(window_k)

        return np.asarray(stoch_k).reshape(-1, 1), np.asarray(stoch_d).reshape(-1, 1)


class SignalOBV:
    """Compute the On-Balance Volume (OBV) for a given price signal."""

    @staticmethod
    def compute_obv(signal: NDArray, volume: NDArray) -> NDArray:
        """
        Compute On-Balance Volume (OBV) given price (e.g., close) and volume arrays.

        Args:
            signal (NDArray): A 1D array of prices (e.g., closing prices).
            volume (NDArray): A 1D array of volumes corresponding to the prices.

        Returns:
            NDArray: A 1D array of OBV values.
        """
        price_1d = signal.squeeze().astype(float)
        vol_1d = volume.squeeze().astype(float)

        obv = np.zeros_like(price_1d)
        for i in range(1, len(price_1d)):
            if price_1d[i] > price_1d[i - 1]:
                obv[i] = obv[i - 1] + vol_1d[i]
            elif price_1d[i] < price_1d[i - 1]:
                obv[i] = obv[i - 1] - vol_1d[i]
            else:
                obv[i] = obv[i - 1]

        return np.asarray(obv).reshape(-1, 1)


class SignalATR:
    """Compute the Average True Range (ATR) for a given price signal."""

    @staticmethod
    def compute_atr(
        high: NDArray, low: NDArray, close: NDArray, window: int = 14
    ) -> NDArray:
        """
        Compute the Average True Range (ATR) for the given price arrays.

        Args:
            high (NDArray): High prices (1D).
            low (NDArray): Low prices (1D).
            close (NDArray): Close prices (1D).
            window (int, optional): The window size for the ATR. Defaults to 14.

        Returns:
            NDArray: A 1D array of ATR values.
        """
        high_1d = high.squeeze().astype(float)
        low_1d = low.squeeze().astype(float)
        close_1d = close.squeeze().astype(float)

        length = len(close_1d)
        if length < 2:
            raise ValueError("Not enough data to compute ATR.")

        # True Range array
        tr = np.empty(length)
        tr[:] = np.nan

        # ATR array
        atr = np.empty(length)
        atr[:] = np.nan

        # True Range for the first period is just (high - low)
        tr[0] = high_1d[0] - low_1d[0]
        atr[0] = tr[0]  # Starting point for ATR

        for i in range(1, length):
            # True Range calculation:
            range1 = high_1d[i] - low_1d[i]
            range2 = abs(high_1d[i] - close_1d[i - 1])
            range3 = abs(low_1d[i] - close_1d[i - 1])
            tr[i] = max(range1, range2, range3)

            # ATR calculation (typical EMA approach)
            if i < window:
                # For initial periods, can use simple average or partial EMA
                atr[i] = np.mean(tr[: i + 1])
            else:
                # ATR(i) = (ATR(i-1) * (window-1) + TR(i)) / window
                atr[i] = (atr[i - 1] * (window - 1) + tr[i]) / window

        return np.asarray(atr).reshape(-1, 1)


async def create_dataset(
    name: str,
    window_size: int,
    tickers_name: List[str],
    interval: str,
    days: str,
    signals: List[DatasetSignal],
    y_signal_source: str,
    c: float,
    n: int,
    use_balancer: bool,
    window_volatility: int,
    momentum_period: int,
    rsi_period: int,
) -> Any:
    """
    Constructs the dataset by extracting signals from each ticker's stock data,
    applying derivative calculations if specified, and combining the data into a single array.
    """
    x_dataset_list: List[NDArray] = []

    y_dataset_list: List[NDArray] = []

    max_initial_na = max(
        window_volatility,
        momentum_period,
        rsi_period,
    )

    y_cls_list, y_ret_list, y_vol_list = [], [], []

    for ticker_name in tickers_name:
        try:
            ticker = TickerHandler(name=ticker_name)

            await ticker.download_data(interval=interval, days=days)

            stock: Optional[pd.DataFrame] = ticker.data.stock

            if stock.shape[0] < window_size:
                continue

            if stock is not None:
                signal_data = []

                signal_data.append(
                    SignalDateTime.compute_time_features(
                        stock.index,
                    ).reshape(-1, 1)
                )

                for signal in signals:
                    if signal.column_name in stock.columns:
                        signal_data.append(
                            np.asarray(stock[signal.column_name].values).reshape(-1, 1)
                        )

                        if signal.is_derivative:
                            derivative: NDArray = SignalDerivative.compute_derivative(
                                stock[signal.column_name]
                            )

                            signal_data.append(derivative.reshape(-1, 1))

                        if signal.is_financial and signal.column_name.lower() in [
                            "close",
                        ]:
                            signal_data.append(
                                SignalMomentum.compute_momentum(
                                    stock[signal.column_name].values.reshape(-1, 1),
                                    momentum_period,
                                ).reshape(-1, 1)
                            )

                            signal_data.append(
                                SignalRSI.compute_rsi(
                                    stock[signal.column_name].values.reshape(-1, 1),
                                    rsi_period,
                                ).reshape(-1, 1)
                            )

                            signal_data += SignalMACD.compute_macd(
                                stock[signal.column_name].values.reshape(-1, 1),
                            )

                            signal_data += (
                                SignalStochasticOscillator.compute_stoch_oscillator(
                                    stock["High"].values.reshape(-1, 1),
                                    stock["Low"].values.reshape(-1, 1),
                                    stock["Close"].values.reshape(-1, 1),
                                )
                            )

                if signal_data:
                    ticker_data = np.concatenate(signal_data, axis=1)

                    ticker_data = ticker_data[max_initial_na:, :]

                    ticker_data = ticker_data[:-n,]

                    ticker_data = create_sliding_window(
                        data=ticker_data, window_size=window_size
                    )

                    if ticker_data is None or np.isnan(np.asarray(ticker_data)).any():
                        continue

                    x_dataset_list.append(ticker_data)

                    nan_count = np.isnan(np.asarray(ticker_data)).sum()

                    y_data = create_binary_signal(
                        signal=stock[y_signal_source][max_initial_na:],
                        c=c,
                        N=n,
                    )[window_size - 1 : -n].reshape(-1, 1)

                    mask = (np.roll(y_data, 1) == 0) & (np.roll(y_data, -1) == 0)

                    y_data[mask] = 0

                    y_cls = y_data.reshape(-1, 1)

                    close = stock["Close"].astype(float).values

                    volume = stock["Volume"].astype(float).values

                    fwd_log_ret = close[n:] - close[:-n]

                    fwd_log_ret = fwd_log_ret[max_initial_na:]

                    fwd_log_ret = fwd_log_ret[window_size - 1 :]

                    y_ret = fwd_log_ret.reshape(-1, 1)

                    roll_std = (
                        pd.Series(volume)
                        .rolling(window_volatility)
                        .std()
                        .shift(-n)
                        .values
                    )

                    roll_std = roll_std[max_initial_na:-n]

                    roll_std = roll_std[window_size - 1 :]

                    y_vol = roll_std.reshape(-1, 1)

                    y_cls_list.append(y_cls)

                    y_ret_list.append(y_ret)

                    y_vol_list.append(y_vol)

        except Exception as e:
            print(f"Error processing ticker {ticker_name}: {e}")

    if not x_dataset_list:
        raise RuntimeError("Dataset vide.")

    X = np.concatenate(x_dataset_list)
    y_cls = np.concatenate(y_cls_list).flatten()
    y_ret = np.concatenate(y_ret_list).flatten()
    y_vol = np.concatenate(y_vol_list).flatten()

    idx = compute_balanced_indices(y_cls)
    X, y_cls, y_ret, y_vol = X[idx], y_cls[idx], y_ret[idx], y_vol[idx]

    # ───── 5. conversion Tensor + Dataset ───────────────────────────────────
    X_t = torch.tensor(X, dtype=torch.float32)
    y_cls = torch.tensor(y_cls, dtype=torch.long)
    y_ret = torch.tensor(y_ret, dtype=torch.float32)
    y_vol = torch.tensor(y_vol, dtype=torch.float32)

    return MultiTaskSignalDataset(X_t, y_cls, y_ret, y_vol)


import numpy as np
import torch
from sklearn.preprocessing import MinMaxScaler
from typing import Union

# feature_ranges = {
#     0: (0.0476190485060215, 0.6726190447807312),
#     1: (0.10119999945163727, 77230.0),
#     2: (-3940.0, 9880.0),
#     3: (-5420.0, 9520.0),
#     4: (0.001832408714108169, 0.9999982714653015),
#     5: (-2711.1240234375, 1537.8070068359375),
#     6: (-1943.899169921875, 1330.8485107421875),
#     7: (-801.3096923828125, 825.0460205078125),
#     8: (0.0, 1.0),
#     9: (0.0, 1.0),
#     10: (0.0, 1197713920.0),
#     11: (-1048523776.0, 1166991104.0)
# }

feature_ranges = {
    0: (0.0476190485060215, 0.6726190447807312),
    1: (0.10119999945163727, 77230.0),
    2: (-3940.0, 9880.0),
    3: (-5420.0, 9520.0),
    4: (0.001832408714108169, 0.9999982714653015),
    5: (-2711.1240234375, 1537.8070068359375),
    6: (-1943.899169921875, 1330.8485107421875),
    7: (-801.3096923828125, 825.0460205078125),
    8: (0.0, 1.0),
    9: (0.0, 1.0),
    10: (0.0, 1197713920.0),
    11: (-1048523776.0, 1166991104.0),
}


def _to_numpy(arr: Union[np.ndarray, torch.Tensor]) -> np.ndarray:
    """Torch → NumPy sans lien au graphe de calcul."""
    if isinstance(arr, torch.Tensor):
        return arr.detach().cpu().numpy()
    return arr


def _to_same_type(arr_np: np.ndarray, ref: Union[np.ndarray, torch.Tensor]):
    """Reconvertit en Torch si `ref` était Torch, sinon laisse en NumPy."""
    if isinstance(ref, torch.Tensor):
        return torch.from_numpy(arr_np).to(ref.device).type_as(ref)
    return arr_np


def scale(
    X: Union[np.ndarray, torch.Tensor], is_use_feature_ranges: bool = True
) -> Union[np.ndarray, torch.Tensor]:
    """
    Mise à l'échelle feature-wise dans [0, 1].

    - Si `is_use_feature_ranges` est True, on prend les bornes pré-enregistrées.
    - Sinon, on calcule min / max sur X et on les affiche pour archivage.

    Garde le même type en sortie qu'en entrée (NumPy <-> Torch).
    """
    # 1) Sauvegarde du type d'origine et conversion NumPy
    X_np = _to_numpy(X)
    n, t, f = X_np.shape
    X_2d = X_np.reshape(-1, f)  # (N*T, F)

    # 2) Détermination des bornes
    if is_use_feature_ranges:
        feature_min = np.array(
            [feature_ranges[i][0] for i in range(f)], dtype=np.float32
        )
        feature_max = np.array(
            [feature_ranges[i][1] for i in range(f)], dtype=np.float32
        )
    else:
        feature_min = X_2d.min(axis=0).astype(np.float32)
        feature_max = X_2d.max(axis=0).astype(np.float32)

        # Affiche les nouvelles bornes
        new_ranges = {
            i: (float(feature_min[i]), float(feature_max[i])) for i in range(f)
        }
        print("Nouveau feature_ranges à sauvegarder :")
        print(new_ranges)

    # 3) Construction manuelle du MinMaxScaler
    scaler = MinMaxScaler(feature_range=(0, 1))
    scaler.n_features_in_ = f
    scaler.data_min_ = feature_min
    scaler.data_max_ = feature_max
    scaler.data_range_ = np.where(
        feature_max - feature_min == 0, 1.0, feature_max - feature_min
    )
    scaler.scale_ = 1.0 / scaler.data_range_
    scaler.min_ = -feature_min * scaler.scale_

    # 4) Transformation puis remise en forme
    X_scaled_2d = scaler.transform(X_2d)
    X_scaled_np = X_scaled_2d.reshape(n, t, f)

    # 5) Retour au type d'origine
    return _to_same_type(X_scaled_np, X)


target_ranges = {"ret": (-8680.0, 14020.0), "vol": (392.421630859375, 354015200.0)}


def scale_target(
    y: Union[np.ndarray, torch.Tensor],
    key: str,  # "ret" ou "vol"
    is_use_saved_ranges: bool = True,
) -> Union[np.ndarray, torch.Tensor]:
    """
    Met y dans [0,1] en conservant le type. Si `is_use_saved_ranges=False`,
    calcule min/max, affiche un dict qu'on pourra coller dans `target_ranges`.
    """
    assert key in ("ret", "vol"), "key doit être 'ret' ou 'vol'"
    y_np = _to_numpy(y).reshape(-1, 1)  # (N,1)

    if is_use_saved_ranges:
        y_min, y_max = target_ranges[key]
    else:
        y_min, y_max = float(y_np.min()), float(y_np.max())
        print(
            f"--> nouveau range pour '{key}': ({y_min}, {y_max}) "
            "→ ajoutez-le dans target_ranges"
        )

    # Min-Max scaling manuel (évite de ré-instancier un MinMaxScaler)
    denom = y_max - y_min if y_max != y_min else 1.0
    y_scaled_np = (y_np - y_min) / denom
    y_scaled_np = np.clip(y_scaled_np, 0.0, 1.0).reshape(-1)  # (N,)

    return _to_same_type(y_scaled_np, y)


import matplotlib.pyplot as plt


def log_ticker_data(
    ticker_name: str,
    x_data: List[NDArray],
    y_data: List[NDArray],
) -> None:
    """
    Logs and plots x and y values for a single ticker on the same plot.

    Args:
        ticker_name (str): Name of the ticker.
        x_data (List[np.ndarray]): List of x values (signals) for the ticker.
        y_data (List[np.ndarray]): List of y values (binary signals) for the ticker.
    """

    plt.figure(figsize=(12, 6))

    plt.plot(list(x_data))

    plt.plot(y_data)

    plt.title(f"X and Y Signals for {ticker_name}")

    plt.xlabel("Index")

    plt.ylabel("Signal Value")

    plt.grid(True)


import math

import torch

import torch.nn as nn


class PositionalEncoding(nn.Module):
    def __init__(self, d_model: int, max_len: int):
        super().__init__()

        pe = torch.zeros(max_len, d_model)
        # (T, d)
        position = torch.arange(0, max_len).unsqueeze(1)  # (T,1)

        div_term = torch.exp(
            torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model)
        )

        pe[:, 0::2] = torch.sin(position * div_term)

        pe[:, 1::2] = torch.cos(position * div_term)

        self.register_buffer("pe", pe.unsqueeze(0))  # (1,T,d)

    def forward(self, x):
        """
        x : (batch, seq_len, d_model)
        """
        return x + self.pe[:, : x.size(1)]


class DilatedTCN(nn.Module):
    def __init__(self, in_ch, hidden_ch, ks=3, n_layers=4):
        super().__init__()
        layers = []
        for i in range(n_layers):
            dilation = 2**i
            pad = (ks - 1) // 2 * dilation
            layers += [
                nn.Conv1d(
                    in_ch if i == 0 else hidden_ch,
                    hidden_ch,
                    ks,
                    dilation=dilation,
                    padding=pad,
                ),
                nn.ReLU(),
            ]
        self.net = nn.Sequential(*layers)

    def forward(self, x):  # x:(B,T,F)
        x = x.transpose(1, 2)  # (B,F,T)
        return self.net(x).transpose(1, 2)  # (B,T,H)


class MultiHeadAttention(nn.Module):
    """
    Multi-head attention mechanism.
    """

    def __init__(self, d_model, n_heads, dropout):
        super(MultiHeadAttention, self).__init__()
        assert d_model % n_heads == 0, "d_model must be divisible by n_heads"

        self.n_heads = n_heads
        self.head_dim = d_model // n_heads

        # Linear projections for query, key, and value for all heads
        self.query_proj = nn.Linear(d_model, d_model)

        self.key_proj = nn.Linear(d_model, d_model)

        self.value_proj = nn.Linear(d_model, d_model)

        # Final projection to combine attention heads
        self.out_proj = nn.Linear(d_model, d_model)

        self.dropout = nn.Dropout(dropout)

        self.scale = self.head_dim**0.5  # Scale factor for stability

    def forward(self, x):
        """
        x: (batch, seq_len, d_model)
        """
        batch_size, seq_len, d_model = x.shape

        # Project the queries, keys, and values
        Q = self.query_proj(x)  # (batch, seq_len, d_model)
        K = self.key_proj(x)  # (batch, seq_len, d_model)
        V = self.value_proj(x)  # (batch, seq_len, d_model)

        # Split the dimensions for multi-head attention
        Q = Q.view(batch_size, seq_len, self.n_heads, self.head_dim).transpose(1, 2)
        K = K.view(batch_size, seq_len, self.n_heads, self.head_dim).transpose(1, 2)
        V = V.view(batch_size, seq_len, self.n_heads, self.head_dim).transpose(1, 2)

        # Compute attention weights
        attn_weights = (
            torch.matmul(Q, K.transpose(-1, -2)) / self.scale
        )  # (batch, n_heads, seq_len, seq_len)

        attn_weights = torch.softmax(attn_weights, dim=-1)

        attn_weights = self.dropout(attn_weights)

        # Apply attention to the values
        attn_output = torch.matmul(
            attn_weights, V
        )  # (batch, n_heads, seq_len, head_dim)

        # Reshape back to (batch, seq_len, d_model)
        attn_output = (
            attn_output.transpose(1, 2).contiguous().view(batch_size, seq_len, d_model)
        )

        # Final linear projection
        output = self.out_proj(attn_output)  # (batch, seq_len, d_model)

        return output, attn_weights


class TransformerEncoderBlock(nn.Module):
    """
    Transformer encoder block that includes multi-head attention with residual connections,
    layer normalization, and a feed-forward network.
    """

    def __init__(self, d_model, n_heads, dropout=0.1, ff_hidden_multiplier=4):
        super(TransformerEncoderBlock, self).__init__()
        self.mha = MultiHeadAttention(d_model, n_heads, dropout)
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)
        self.ff = nn.Sequential(
            nn.Linear(d_model, d_model * ff_hidden_multiplier),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(d_model * ff_hidden_multiplier, d_model),
        )

    def forward(self, x):
        # Multi-head attention sub-layer with residual connection and layer normalization
        attn_output, attn_weights = self.mha(x)
        x = self.norm1(x + self.dropout(attn_output))

        # Feed-forward sub-layer with residual connection and layer normalization
        ff_output = self.ff(x)
        x = self.norm2(x + self.dropout(ff_output))
        return x


class TransformerEncoderBlockPreNorm(nn.Module):
    def __init__(self, d_model, n_heads, p_attn=0.1, p_ff=0.3, ff_mult=4):
        super().__init__()

        self.norm1 = nn.LayerNorm(d_model)
        self.mha = MultiHeadAttention(d_model, n_heads, dropout=p_attn)
        self.drop_attn = nn.Dropout(p_attn)

        self.norm2 = nn.LayerNorm(d_model)
        self.ff = nn.Sequential(
            nn.Linear(d_model, d_model * ff_mult),
            nn.GELU(),  # ← ReLU → GELU
            nn.Dropout(p_ff),
            nn.Linear(d_model * ff_mult, d_model),
        )
        self.drop_ff = nn.Dropout(p_ff)

    def forward(self, x):
        # ─── Pre-Norm Multi-Head Attention ──────────────────────
        y = self.norm1(x)
        attn_out, _ = self.mha(y)
        x = x + self.drop_attn(attn_out)

        # ─── Pre-Norm Feed-Forward ─────────────────────────────
        y = self.norm2(x)
        ff_out = self.ff(y)
        x = x + self.drop_ff(ff_out)
        return x


class AttentionPooling(nn.Module):
    """
    Learned attention pooling mechanism. Instead of using a simple mean pooling,
    this module learns to weight different time steps.
    """

    def __init__(self, hidden_size):
        super(AttentionPooling, self).__init__()
        # Initialize a learnable attention vector
        self.attn_vector = nn.Parameter(torch.randn(hidden_size))
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        """
        x: (batch, seq_len, hidden_size)
        Returns a pooled representation: (batch, hidden_size)
        """
        # Compute attention scores for each time step
        scores = torch.matmul(x, self.attn_vector)  # (batch, seq_len)
        weights = self.softmax(scores).unsqueeze(-1)  # (batch, seq_len, 1)
        pooled = torch.sum(x * weights, dim=1)  # (batch, hidden_size)
        return pooled


class PatchEmbed(nn.Module):
    """
    Découpe la séquence (T, F) en patches contigus de taille `patch_size`
    puis projette chaque patch en un vecteur `d_model`.
    - Si T n’est pas multiple de patch_size, on zero-pad la fin.
    """

    def __init__(self, in_ch: int, patch_size: int = 16, d_model: int = 128):
        super().__init__()
        self.ps = patch_size
        self.proj = nn.Linear(in_ch * patch_size, d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x : (B, T, F)
        B, T, F = x.shape
        pad = (-T) % self.ps  # pour avoir un nombre entier de patches
        if pad:
            x = torch.cat([x, x.new_zeros(B, pad, F)], dim=1)

        n_patches = x.size(1) // self.ps
        x = x.view(B, n_patches, self.ps * F)  # (B, n_p, ps·F)
        return self.proj(x)  # (B, n_p, d_model)


class SimpleModel(nn.Module):
    def __init__(
        self,
        num_historical_features: int,
        encoder_length: int,
        hidden_size: int = 1024,
        dropout: float = 0.1,
        lstm_layers: int = 1,
        n_heads: int = 4,
        num_attention_layers: int = 3,
        pooling_type: str = "attn",
        patch_size: int = 128,
    ):
        """
        pooling_type:
          - "mean": simple average over time steps
          - "last": use the LSTM's final hidden state
          - "attn": use a learned attention pooling mechanism
        """
        super(SimpleModel, self).__init__()
        self.encoder_length = encoder_length
        self.hidden_size = hidden_size
        self.n_heads = n_heads
        self.num_attention_layers = num_attention_layers
        self.pooling_type = pooling_type

        self.input_proj = nn.Linear(num_historical_features, hidden_size)

        self.patch_embed = PatchEmbed(
            num_historical_features, patch_size=patch_size, d_model=hidden_size
        )

        n_patches = math.ceil(encoder_length / patch_size)

        self.pos_enc = PositionalEncoding(hidden_size, max_len=n_patches)

        self.tcn = DilatedTCN(
            in_ch=hidden_size, hidden_ch=hidden_size, ks=3, n_layers=4
        )

        self.encoder_lstm = nn.LSTM(
            hidden_size,
            hidden_size,
            num_layers=lstm_layers,
            batch_first=True,
            dropout=dropout if lstm_layers > 1 else 0.0,
        )

        # Stack multiple Transformer encoder blocks (attention layers)
        self.attention_layers = nn.ModuleList(
            [
                TransformerEncoderBlockPreNorm(
                    hidden_size, n_heads, p_attn=0.1, p_ff=0.3
                )
                for _ in range(num_attention_layers)
            ]
        )

        # self.attention_layers = nn.ModuleList(
        #     [
        #         TransformerEncoderBlock(
        #             d_model=hidden_size, n_heads=n_heads, dropout=dropout
        #         )
        #         for _ in range(num_attention_layers)
        #     ]
        # )

        self.pool = AttentionPooling(hidden_size)

        # Final classification layer (adjust output size as needed)
        self.fc_out = nn.Sequential(
            nn.Linear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size // 2, 3),  # 3 output logits
        )

        self.ret_head = nn.Linear(hidden_size, 1)  # régression

        self.vol_head = nn.Linear(hidden_size, 1)

    def forward(self, historical_input):
        """
        historical_input: shape (batch, encoder_length, num_historical_features)
        """
        # 1) Project input to hidden_size
        x = self.patch_embed(historical_input)

        # x = self.input_proj(historical_input)

        x = self.pos_enc(x)

        x = self.tcn(x)

        # 2) LSTM encoding
        enc_output, (h, c) = self.encoder_lstm(
            x
        )  # enc_output: (batch, seq_len, hidden_size)

        # Apply stacked attention layers
        for layer in self.attention_layers:
            enc_output = layer(enc_output)

            # Learned attention pooling
        seq_rep = self.pool(enc_output)  # (batch, hidden_size)

        # 4) Final classification (logits)
        logits = self.fc_out(seq_rep)  # (batch, 3)

        ret_pred = self.ret_head(seq_rep).squeeze(-1)

        vol_pred = self.vol_head(seq_rep).squeeze(-1)

        return {"logits": logits, "ret_pred": ret_pred, "vol_pred": vol_pred}


from typing import List

import numpy as np

from sqlalchemy import all_
import torch

import torch.nn as nn

from torch.optim import AdamW

from torch.utils.data import DataLoader, TensorDataset

from IPython.display import display, clear_output, Image

from torch.optim.lr_scheduler import OneCycleLR


def initialize_weights(m):
    if isinstance(m, nn.Linear):
        nn.init.xavier_uniform_(m.weight)

        if m.bias is not None:
            nn.init.zeros_(m.bias)

    elif isinstance(m, nn.LSTM):
        for name, param in m.named_parameters():
            if "weight" in name:
                nn.init.xavier_uniform_(param)

            elif "bias" in name:
                nn.init.zeros_(param)


class Trainer:
    def __init__(
        self,
        signals: List,  # List of DatasetSignal if needed
        ticker_dataset_train,  # Assumed external dataset type
        ticker_dataset_val,  # Assumed external dataset type
        model: nn.Module,
        model_save_path: str,
        batch_size: int,
        lr: float,
        weight_decay: float,
        windows_size: int,
    ) -> None:
        self.signals = signals

        self.ticker_dataset_train = ticker_dataset_train

        self.ticker_dataset_val = ticker_dataset_val

        self.model = model

        self.model.apply(initialize_weights)

        self.model_save_path = model_save_path

        self.batch_size = batch_size

        self.lr = lr

        self.weight_decay = weight_decay

        self.windows_size = windows_size

        if not os.path.exists(self.model_save_path):
            os.makedirs(self.model_save_path)

        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = self.model.to(self.device)

        plt.ion()

        self.fig, self.ax = plt.subplots(figsize=(10, 5))

    def loss_fn(
        self,
        outputs,
        y_cls,
        y_ret=None,
        y_vol=None,
        alpha_cls=1.0,
        beta_ret=0.25,
        gamma_vol=0.01,
    ):
        class_weights = torch.tensor([1.0, 1.0, 2.0], device=self.device)

        cls_loss = nn.CrossEntropyLoss(weight=class_weights)(outputs["logits"], y_cls)

        ret_loss = nn.SmoothL1Loss()(outputs["ret_pred"], y_ret)

        vol_loss = nn.SmoothL1Loss()(outputs["vol_pred"], y_vol)

        return alpha_cls * cls_loss + beta_ret * ret_loss + gamma_vol * vol_loss

    @staticmethod
    def model_name_creator(
        model_type: str,
        tickers_type: str,
        signals_type: str,
        gain: int,
        n: int,
        window_size: int,
    ) -> str:
        return f"{model_type}_{tickers_type}_{signals_type}_{gain}_{n}_{window_size}"

    def train(self) -> None:
        while not self.fit_model(
            train_dataset=self.ticker_dataset_train, val_dataset=self.ticker_dataset_val
        ):
            pass

    def fit_model(
        self, train_dataset: TensorDataset, val_dataset: TensorDataset
    ) -> bool:
        max_epochs = 1000

        train_loader = DataLoader(
            dataset=train_dataset, batch_size=self.batch_size, shuffle=True
        )

        val_loader = DataLoader(
            dataset=val_dataset, batch_size=self.batch_size, shuffle=False
        )

        criterion = self.loss_fn

        optimizer = AdamW(
            self.model.parameters(), lr=self.lr, weight_decay=self.weight_decay
        )

        scheduler = OneCycleLR(
            optimizer,
            max_lr=5e-4,
            steps_per_epoch=len(train_loader),
            epochs=max_epochs,
            pct_start=0.3,
            anneal_strategy="cos",
        )

        model_save_path = "/content/drive/MyDrive"

        model_filename = "model_epoch_4_50.pth"

        full_path = os.path.join(model_save_path, model_filename)

        start_epoch = 0

        if False:  # os.path.exists(full_path):
            checkpoint = torch.load(full_path, weights_only=False)

            self.model.load_state_dict(checkpoint["model_state_dict"])

            start_epoch = checkpoint["epoch"]

            print(f"Loaded checkpoint from '{full_path}' at epoch {start_epoch}.")

        else:
            print(f"No checkpoint found at '{full_path}'. Starting from scratch.")

        # Lists to store predictions and targets for plotting.

        all_losses = []

        all_losses_train = []

        all_ratio = []

        all_ration_2 = []

        all_ratio_2_train = []

        for epoch in range(start_epoch, max_epochs):
            self.model.train()
            epoch_train_losses = []

            all_train_predictions = []

            all_train_targets = []

            for batch_x, tgt in train_loader:
                batch_x = batch_x.to(self.device)

                y_cls = tgt["cls"].to(self.device)  # (B,)

                y_ret = tgt["ret"].to(self.device)  # (B,)

                y_vol = tgt["vol"].to(self.device)  # (B,)

                outs = self.model(historical_input=batch_x)

                loss = criterion(outs, y_cls, y_ret, y_vol)

                optimizer.zero_grad()

                loss.backward()

                torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=100)

                optimizer.step()

                scheduler.step()

                epoch_train_losses.append(loss.item())

                preds = outs["logits"].argmax(dim=1).cpu().detach().numpy()

                all_train_predictions.extend(preds)

                all_train_targets.extend(y_cls.cpu().detach().numpy())

            avg_train_loss = np.mean(epoch_train_losses)

            all_losses_train.append(avg_train_loss)

            # Validation evaluation
            self.model.eval()
            epoch_val_losses = []
            all_val_predictions = []
            all_val_targets = []

            with torch.no_grad():
                for batch_x, tgt in val_loader:
                    batch_x = batch_x.to(self.device)
                    y_cls = tgt["cls"].to(self.device)
                    y_ret = tgt["ret"].to(self.device)
                    y_vol = tgt["vol"].to(self.device)

                    outs = self.model(historical_input=batch_x)

                    loss = criterion(outs, y_cls, y_ret, y_vol)

                    preds = outs["logits"].argmax(dim=1).cpu().detach().numpy()

                    epoch_val_losses.append(loss.item())

                    all_val_predictions.extend(preds)

                    all_val_targets.extend(y_cls.cpu().detach().numpy())

            nb_0_pred = np.sum(np.array(all_val_predictions) == 0)

            nb_1_pred = np.sum(np.array(all_val_predictions) == 1)

            nb_2_pred = np.sum(np.array(all_val_predictions) == 2)

            nb_real_2 = np.sum(
                (np.array(all_val_predictions) == 2) & (np.array(all_val_targets) == 2)
            )

            ratio_2_false = nb_real_2 / nb_2_pred

            nb_real_2_extend_1 = np.sum(
                (np.array(all_val_predictions) == 2)
                & ((np.array(all_val_targets) == 2) | (np.array(all_val_targets) == 1))
            )

            ratio_2_false_extend_1 = nb_real_2_extend_1 / nb_2_pred

            nb_O_pred_train = np.sum(np.array(all_train_predictions) == 0)

            nb_1_pred_train = np.sum(np.array(all_train_predictions) == 1)

            nb_2_pred_train = np.sum(np.array(all_train_predictions) == 2)

            nb_real_2_train = np.sum(
                (np.array(all_train_predictions) == 2)
                & (np.array(all_train_targets) == 2)
            )

            ratio_2_false_train = nb_real_2_train / nb_2_pred_train

            nb_real_2_extend_1_train = np.sum(
                (np.array(all_train_predictions) == 2)
                & (
                    (np.array(all_train_targets) == 2)
                    | (np.array(all_train_targets) == 1)
                )
            )

            ratio_2_false_extend_1_train = nb_real_2_extend_1_train / nb_2_pred_train

            avg_val_loss = np.mean(epoch_val_losses)

            all_losses.append(avg_val_loss)

            all_ratio.append(ratio_2_false)

            all_ration_2.append(ratio_2_false_extend_1)

            all_ratio_2_train.append(ratio_2_false_extend_1_train)

            self.plot_live_predictions(
                np.array(all_val_predictions),
                np.array(all_val_targets),
                np.array(all_train_predictions),
                np.array(all_train_targets),
                all_losses,
                all_ratio,
                all_ration_2,
                all_losses_train,
                all_ratio_2_train,
            )

            print(
                f"Epoch {epoch + 1}/{max_epochs}, Train Loss: {avg_train_loss:.5f}, Val Loss: {avg_val_loss:.5f}"
            )

            print()

            print(f"Nb 0 : {nb_0_pred}, Nb 1 : {nb_1_pred}, Nb 2 : {nb_2_pred}")

            print(f"Ratio 2 true : {ratio_2_false:.4} ({nb_real_2} / {nb_2_pred})")

            print(
                f"Ratio 2 true extend 1 : {ratio_2_false_extend_1:.4} ({nb_real_2_extend_1} / {nb_2_pred})"
            )

            print()

            print(
                f"Nb 0 train : {nb_O_pred_train}, Nb 1 train : {nb_1_pred_train}, Nb 2 train : {nb_2_pred_train}"
            )

            print(
                f"Ratio 2 true train : {ratio_2_false_train:.4} ({nb_real_2_train} / {nb_2_pred_train})"
            )

            print(
                f"Ratio 2 true extend 1 train : {ratio_2_false_extend_1_train:.4} ({nb_real_2_extend_1_train} / {nb_2_pred_train})"
            )

            # Checkpoint saving (every 5 epochs)
            if (epoch + 1) % 2 == 0:
                prev_path = f"/content/drive/MyDrive/model_epoch_4_{epoch - 1}.pth"

                if os.path.exists(prev_path):
                    os.remove(prev_path)

                    print(f"Ancien checkpoint supprimé : {prev_path}")

                checkpoint_path = os.path.join(
                    "/content/drive/MyDrive", f"model_epoch_4_{epoch + 1}.pth"
                )

                torch.save(
                    {
                        "epoch": epoch + 1,
                        "model_state_dict": self.model.state_dict(),
                        "optimizer_state_dict": optimizer.state_dict(),
                        "loss": avg_train_loss,
                    },
                    checkpoint_path,
                )
                print(f"Checkpoint saved at epoch {epoch + 1}.")

        return True

    def plot_live_predictions(
        self,
        predictions_val,
        targets_val,
        predictions_train,
        targets_train,
        all_losses,
        all_ratio,
        all_ration_2,
        all_losses_train,
        all_ratio_2_train,
    ):
        """
        Crée un graphique avec deux lignes : en haut, les sous-graphiques pour la validation et l'entraînement;
        en bas, le graphique de la perte.
        """
        import matplotlib.gridspec as gridspec

        def create_subplot(ax, pred, true, dataset_name):
            order = np.argsort(true)
            sorted_true = true[order]
            sorted_pred = pred[order]
            x_axis = np.arange(len(sorted_true))
            ax.scatter(x_axis, sorted_true, color="blue", label="Actual", s=10)
            ax.scatter(
                x_axis, sorted_pred, color="red", marker="x", label="Predicted", s=3
            )
            ax.set_title(f"{dataset_name} Dataset")
            ax.set_xlabel("Sorted Sample Index")
            ax.set_ylabel("Class")
            ax.set_yticks([0, 1, 2])
            ax.legend()

        fig = plt.figure(figsize=(16, 8))
        gs = gridspec.GridSpec(3, 2, height_ratios=[1, 1, 1])

        ax_val = fig.add_subplot(gs[0, 0])  # 1ère ligne, 1ère colonne
        ax_train = fig.add_subplot(gs[0, 1])  # 1ère ligne, 2ème colonne
        ax_loss = fig.add_subplot(gs[1, 0])  # 2ème ligne, 1ère colonne
        ax_ratio = fig.add_subplot(gs[1, 1])  # 2ème ligne, 2ème colonne
        ax_loss_train = fig.add_subplot(gs[2, 0])  # 2ème ligne, 2ème colonne
        ax_ratio_train = fig.add_subplot(gs[2, 1])  # 2ème ligne, 2ème colonne

        create_subplot(ax_val, predictions_val, targets_val, "Validation")
        create_subplot(ax_train, predictions_train, targets_train, "Training")

        # Plot de la loss
        x_axis = np.arange(len(all_losses))
        ax_loss.plot(x_axis, all_losses, color="green", marker="o", label="Loss")
        ax_loss.set_title("Loss")
        ax_loss.set_xlabel("Epoch")
        ax_loss.set_ylabel("Loss")

        # Plot du ratio
        ax_ratio.plot(x_axis, all_ration_2, color="red", marker="o", label="Ratio 2")
        ax_ratio.set_title("Ratio 2")
        ax_ratio.set_xlabel("Epoch")
        ax_ratio.set_ylabel("Ratio")

        ax_loss_train.plot(
            x_axis, all_losses_train, color="red", marker="o", label="Loss train"
        )
        ax_loss_train.set_title("Loss train")
        ax_loss_train.set_xlabel("Epoch")
        ax_loss_train.set_ylabel("Loss")

        ax_ratio_train.plot(
            x_axis, all_ratio_2_train, color="red", marker="o", label="Ratio train"
        )
        ax_ratio_train.set_title("Ratio train")
        ax_ratio_train.set_xlabel("Epoch")
        ax_ratio_train.set_ylabel("Ratio train")

        plt.tight_layout()
        plot_path = "./live_plot.png"
        plt.savefig(plot_path, bbox_inches="tight")
        clear_output(wait=True)
        display(Image(filename=plot_path))
        plt.close(fig)


import random


signals = [
    DatasetSignal(
        column_name="Close",
        is_derivative=True,
        is_normalize=True,
        is_financial=True,
    ),
    DatasetSignal(
        column_name="Volume",
        is_derivative=True,
        is_normalize=True,
        is_financial=False,
    ),
]

c = 0.2

n = 40

window_size = 1000

batch_size = 128

interval = "1h"

day = "729"

ticker_name_type = "company_crypto"

tickers_name_train = tickers_yahoo


crypto = list(set(tickers_name_train))

random.shuffle(crypto)


split_dataset = int(len(crypto) * 0.95)

tickers_name_train = crypto[:split_dataset]

tickers_name_val = crypto[split_dataset:]

print(f"Crypto : {len(crypto)}")

print(f"Ticker train : {len(tickers_name_train)}")

print(f"Ticker val : {len(tickers_name_val)}")

step = 20


ticker_dataset_train = await create_dataset(
    name="TRAIN",
    tickers_name=tickers_name_train[:step],
    interval=interval,
    days=day,
    signals=signals,
    y_signal_source="Close",
    window_size=window_size,
    c=c,
    n=n,
    window_volatility=14,
    momentum_period=5,
    rsi_period=5,
    use_balancer=True,
)

print("\n\n\n-----------------------------------------\n\n\n")

for i in range(step, len(tickers_name_train), step):
    print(f"{int(i / step)} / {int(len(tickers_name_train) / step)}")

    ticker_dataset_train_batch = await create_dataset(
        name="TRAIN",
        tickers_name=tickers_name_train[i : i + step],
        interval=interval,
        days=day,
        signals=signals,
        y_signal_source="Close",
        window_size=window_size,
        c=c,
        n=n,
        window_volatility=14,
        momentum_period=5,
        rsi_period=5,
        use_balancer=True,
    )

    ticker_dataset_train.X = np.concatenate(
        (ticker_dataset_train.X, ticker_dataset_train_batch.X), axis=0
    )

    ticker_dataset_train.y_cls = np.concatenate(
        (ticker_dataset_train.y_cls, ticker_dataset_train_batch.y_cls), axis=0
    )

    ticker_dataset_train.y_vol = np.concatenate(
        (ticker_dataset_train.y_vol, ticker_dataset_train_batch.y_vol), axis=0
    )

    ticker_dataset_train.y_ret = np.concatenate(
        (ticker_dataset_train.y_ret, ticker_dataset_train_batch.y_ret), axis=0
    )

    print(f"Ticker train X : {len(ticker_dataset_train.X)}")

    print(f"Ticker train Y : {len(ticker_dataset_train.y_cls)}")

    print(f"Ticker train Y : {len(ticker_dataset_train.y_vol)}")

    print(f"Ticker train Y : {len(ticker_dataset_train.y_ret)}")

    print("\n\n\n-----------------------------------------\n\n\n")

ticker_dataset_val = await create_dataset(
    name="VAL",
    tickers_name=tickers_name_val[:step],
    interval=interval,
    days=day,
    signals=signals,
    y_signal_source="Close",
    window_size=window_size,
    c=c,
    n=n,
    use_balancer=True,
    window_volatility=14,
    momentum_period=5,
    rsi_period=5,
)


for i in range(step, len(tickers_name_val), step):
    print(tickers_name_val[i : i + step])

    try:
        ticker_dataset_val_batch = await create_dataset(
            name="VAL",
            tickers_name=tickers_name_val[i : i + step],
            interval=interval,
            days=day,
            signals=signals,
            y_signal_source="Close",
            window_size=window_size,
            c=c,
            n=n,
            window_volatility=14,
            momentum_period=5,
            rsi_period=5,
            use_balancer=True,
        )

        ticker_dataset_val.X = np.concatenate(
            (ticker_dataset_val.X, ticker_dataset_val_batch.X), axis=0
        )

        ticker_dataset_val.y_cls = np.concatenate(
            (ticker_dataset_val.y_cls, ticker_dataset_val_batch.y_cls), axis=0
        )

        ticker_dataset_val.y_ret = np.concatenate(
            (ticker_dataset_val.y_ret, ticker_dataset_val_batch.y_ret), axis=0
        )

        ticker_dataset_val.y_vol = np.concatenate(
            (ticker_dataset_val.y_vol, ticker_dataset_val_batch.y_vol), axis=0
        )

    except Exception as e:
        print(e)

    print(f"Ticker val X : {len(ticker_dataset_val.X)}")

    print(f"Ticker val Y : {len(ticker_dataset_val.y_cls)}")

    print(f"Ticker val Y : {len(ticker_dataset_val.y_ret)}")

    print(f"Ticker val Y : {len(ticker_dataset_val.y_vol)}")


ticker_dataset_train.X = scale(X=ticker_dataset_train.X, is_use_feature_ranges=True)

ticker_dataset_val.X = scale(X=ticker_dataset_val.X, is_use_feature_ranges=True)

ticker_dataset_train.y_ret = scale_target(
    ticker_dataset_train.y_ret, key="ret", is_use_saved_ranges=True
)

ticker_dataset_train.y_vol = scale_target(
    ticker_dataset_train.y_vol, key="vol", is_use_saved_ranges=True
)


ticker_dataset_val.y_ret = scale_target(
    ticker_dataset_val.y_ret, key="ret", is_use_saved_ranges=True
)

ticker_dataset_val.y_vol = scale_target(
    ticker_dataset_val.y_vol, key="vol", is_use_saved_ranges=True
)


print(f"Max X : {np.max(np.asarray(ticker_dataset_train.X))}")

print(f"Min X : {np.min(np.asarray(ticker_dataset_train.X))}")

print(f"Max Y : {np.max(np.asarray(ticker_dataset_train.y_cls))}")

print(f"Min Y : {np.min(np.asarray(ticker_dataset_val.y_cls))}")

print(f"Max Y : {np.max(np.asarray(ticker_dataset_train.y_ret))}")

print(f"Min Y : {np.min(np.asarray(ticker_dataset_val.y_ret))}")

print(f"Max Y : {np.max(np.asarray(ticker_dataset_train.y_vol))}")

print(f"Min Y : {np.min(np.asarray(ticker_dataset_val.y_vol))}")

import gc
import torch

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

lr = 1.0e-4

weight_decay = 1.0e-3

model = SimpleModel(
    num_historical_features=ticker_dataset_train.X.shape[
        2
    ],  # Number of historical features
    encoder_length=window_size,  # Length of past history
    hidden_size=1024 * 2,  # Hidden size of embeddings
    dropout=0.3,  # Dropout rate
    lstm_layers=2 * 4,  # Number of LSTM layers in encoder and decoder
    n_heads=4 * 8,
    num_attention_layers=4 * 4,
    patch_size=int(window_size / 4),
)

model_nb_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

model_size_in_b = model_nb_params / 1e9

print(f"Model size: {model_nb_params} parameters")

print(f"Model size: {model_size_in_b:.3f}B parameters")

model_name: str = Trainer.model_name_creator(
    model_type=model._get_name(),
    tickers_type=ticker_name_type,
    signals_type="high_volume",
    gain=c,
    n=n,
    window_size=window_size,
)

path: str = f"./app/trainer/models/{model_name}"

print(f"Will save on {path}")

print(f"Ticker train X : {len(ticker_dataset_train.X)}")

print(f"Ticker train Y : {len(ticker_dataset_train.y_cls)}")

print(f"Ticker train Y : {len(ticker_dataset_train.y_ret)}")

print(f"Ticker train Y : {len(ticker_dataset_train.y_vol)}")

print(f"Ticker val X : {ticker_dataset_val.X.shape}")

print(f"Ticker val Y : {ticker_dataset_val.y_cls.shape}")

print(f"Ticker val Y : {ticker_dataset_val.y_ret.shape}")

print(f"Ticker val Y : {ticker_dataset_val.y_vol.shape}")


trainer = Trainer(
    signals=signals,
    ticker_dataset_train=ticker_dataset_train,
    ticker_dataset_val=ticker_dataset_val,
    model=model,
    model_save_path=path,
    batch_size=batch_size,
    lr=lr,
    weight_decay=weight_decay,
    windows_size=window_size,
)

trainer.train()
